version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: uber-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=uber_simulation

  redis:
    image: redis:latest
    container_name: uber-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data: 