_format_version: "3.0"
_transform: true # Enables shorter syntax where applicable

# --- Consumer Definition ---
consumers:
  - username: auth-service-consumer # Identifier for the consumer (can be iss value)
    custom_id: auth-service-consumer # Or use a simple custom_id for easier reference

# --- JWT Secret (JWKS) Definition ---
# This is the correct top-level key for JWT credentials
jwt_secrets:
  - consumer: auth-service-consumer # Reference consumer by username or custom_id
    algorithm: RS256               # Explicitly set the algorithm
    key: "https://my-auth-service.com" # A UNIQUE IDENTIFIER for this credential.
                                      # This value MUST match the 'iss' claim in your JWT.
                                      # Or, if you keep using 'iss' for the issuer URL in your JWT,
                                      # set key_claim_name: kid in the JWT plugin config and put
                                      # this value in the 'kid' header of your JWT.
    rsa_public_key: |                 # The actual public key content in PEM format
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1SRvfSND6yNouXxNkOWZ
      PQ0691YyQ49ffI2Ja+c/FtJmzMUgQ4/3bJuZ3AqkNJaPsRK4lWGGWCvdl1x374mO
      UgPJ+cFZr1OqbAqNc7qrnIhd1Kg3CyiNhSpRMjf1KeXxSLRyFnh7jcYK/H0RjwHY
      z/yhKN2XGymxktZZIjS5jPRr3kmNNTdVZtbJHPbuixWMI3pwx8B+kgtu4PM7fCSC
      DDnlW/8rV1hrAkRoYhiAc9eDH1N1dA0acfWm692T2LtbJubSGriyIRpySye0eHQB
      Ii5bYMpIgITBwe50hfp70a7tcDXK2wkGtDlVHs6oNsrJtqE4yghlAENcmhqRZFGp
      4wIDAQAB
      -----END PUBLIC KEY-----

    # secret: "dummy-secret-if-needed" # Add this ONLY if required by decK/Ingress Controller context
                                     # Otherwise, omit or set to null. Setting null is safer.
    secret: null

# --- Service Definitions ---
services:
  # --- Auth Service Definition ---
  - name: auth-service
    url: http://auth-service:3000 # Internal service name and port
    routes:
      - name: auth-public-routes
        paths:
          - /api/v1/auth/login
          - /api/v1/auth/register/customer
          - /api/v1/auth/register/driver
        strip_path: false
        # This route should NOT have JWT validation
      - name: auth-jwks-route
        paths:
          - /.well-known/jwks.json
        strip_path: false
        # This route should NOT have JWT validation

  # --- Example: Driver Service Definition (Protected) ---
  - name: driver-service
    # IMPORTANT: Make sure 'driver-service' is defined in your docker-compose.yml
    # and running on port 3001 within the 'app-network'
    url: http://driver-service:3001
    plugins:
      - name: jwt
        config:
          key_claim_name: iss       # Look for the 'iss' claim in the JWT
          claims_to_verify:       # Verify standard claims
            - exp                 # Check token expiry
          run_on_preflight: true
    
    routes:
      - name: driver-routes
        paths:
          - /api/v1/drivers
        strip_path: false
        # The JWT plugin applied to the service will protect this route

# --- Add other microservices similarly ---